export const formFields = {
	audio: '',
	sample_audio: '',
	posttype: '',
	url: '',
	price: '',
	name: '',
	description: '',
	cover_pic: '',
	author_name: '',
	soical_media_name: '',
	genre: '',
	ismb: '',
	rating: '',
	sale_price: '',
	fiction: '',
	released_date: '',
	rsb: 0,
	peek: '',
	lbr: 0,
	pages: '',
};

export const errorFields = {
	posttype: '',
	url: '',
	price: '',
	name: '',
	description: '',
	sample_audio: '',
	audio: '',
	cover_pic: '',
	author_name: '',
	soical_media_name: '',
	genre: '',
	rating: '',
	fiction: '',
	released_date: '',
	peek: '',
	pages: '',
};

export const errorEditFields = {
	post_type: '',
	price: '',
	title: '',
	description: '',
	author_name: '',
	soical_media_name: '',
	genre: '',
	rating: '',
	fiction: '',
	released_date: '',
	peek: '',
};

export const types = ['image/*', '.epub, .mobi', 'audio/*', '.epub, .mobi'];
